### ISSUE TITLE
feat: selection of matrix distances via LED stripes specification

### ISSUE THREAD

**Issue by SimonGolms** [SimonGolms/QLOCKGENERATOR#7]
The calculation of the distances of the LED matrix should be possible e.g. via a dropdown list of the LED Stripes (30 LED/m; 60 LED/m; 144 LED/m) specification.

**Comment by BjoeHrn** [comment]
Hi, 

is this feature now avaible? Or can you tell me how I can use this generator for a 60 LED/m stripe?
Sorry for my bad english…

Thanks for you're answer :-)

**Comment by SimonGolms** [comment]
Unfortunately, I didn't have time to implement this feature yet. A Pull request is very welcome.

**Comment by just-jason** [comment]
This would be very useful

**Comment by SimonGolms** [comment]
Hi, I am currently working on the implementation of this feature, how exactly did you think about the stripes length selection?
Currently you could enter the number of LEDs/meters and they will be calculated centered, the distance between the LEDs is the same vertically and horizontally. Does that make sense?

In the meantime, I will provide an updated version in the next days:
![image](https://user-images.githubusercontent.com/17799657/71714041-868b9000-2e0c-11ea-9ede-cb8ddd7ede24.png)

**Comment by BjoeHrn** [comment]
Good morning Simon,

it will be very important, that the space between the stripes is the right one. Otherwise you have to correct the hole layout or use single WS2812B LEDs, The distance between the LEDs in vertical an horzizontal position should be the same.
For Example you choose the stripe with 60 LEDs per meter. The space between each LED have to be 16,66 mm vertical and horizontal. The hole Layout should be centered - that looks good.

I hope this help you a littel bit?

*********

In german: 

Da mein Englisch nicht so gut ist , schreibe ich es nochmal in Deutsch . So wie du es planst klingt es sehr gut. Das gesamte Layout sollte mittig gesetzt werden. Der Abstand zwischen den LEDs in der horizontalen sollte genauso sein wie in der vertikalen. Wichtig ist es nur, dass der Abstand zwischen den LEDs dem tatsächlichen Abstand entspricht. Also bei dem 60 LEDs / m Stripe beträgt der Abstand von Mitte LED zu Mitte LED 16,66 mm.

**Comment by SimonGolms** [comment]
With the latest PR #25 the change is now available. The calculations should be valid but it would be great if this could be confirmed from someone else, too.

**Comment by BjoeHrn** [comment]
Hello Simon,

I checked the spaces in my CAD program and it looks very good.

30 LEDs per Meter (500x500mm):
![Spaces_30ledsm](https://user-images.githubusercontent.com/47157136/71887256-05026d80-313e-11ea-87f9-8b5a9d0d60bd.PNG)

60 LEDs per Meter (230x230mm):
![Spaces_60ledsm](https://user-images.githubusercontent.com/47157136/71887300-15b2e380-313e-11ea-9709-953396a60d6f.PNG)

The distance between the LEDs is on two decimal places perfect :-)!

Thanks a lot for your work!

**Comment by SimonGolms** [comment]
Hi @BjoeHrn, thanks for the confirmation.
